[package]
name = "mine_block"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = true
panic = "abort"

[dependencies]
anyhow = "1.0.95"
hex = "0.4.3"
rayon = "1.10.0"
sha2 = "0.10.8"
thiserror = "2.0.11"
